#
# Makefile for a linux user module and wiringPi
#
# Copyright 2020 Felix Knorre  <felix-knorre@hotmail.de>
#

readMod : readMod.c
	gcc -Wall -o readMod readMod.c -lwiringPi -lwiringPiDev
	
clean : 
	rm readMod
